In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [106]:
## your code
np.ones(20)/np.arange(1, 21)*(2**np.arange(1, 21))

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [15]:
## your code
(0.1**(3*np.arange(6))*0.2**(4*(np.arange(6)))).sum()

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [44]:
## your code
A = np.zeros((8,8),dtype=int)
A[0::2,::2] = 1
A[1::2,1::2] = 1
A

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [101]:
X = np.random.random((5, 2))

## your code
print('X = ', X)
@np.vectorize
def to_polar(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return rho, phi
Y = np.array(to_polar(X[:,0], X[:,1])).T
Y

X =  [[0.11083226 0.53007441]
 [0.9637118  0.75843638]
 [0.1040908  0.93156181]
 [0.30301021 0.69907578]
 [0.53178923 0.19758236]]


array([[0.54153732, 1.36467767],
       [1.22636298, 0.66676062],
       [0.93735921, 1.45951996],
       [0.76192003, 1.16179532],
       [0.56730818, 0.35573609]])

**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [16]:
X = np.random.random((10, 10))

## your code
print(X)
np.unravel_index(np.argmax(X, axis=None), X.shape)

[[0.89427799 0.45751621 0.92703258 0.6109074  0.94975313 0.98771186
  0.17797825 0.84847369 0.6780394  0.16726315]
 [0.79050458 0.23859442 0.12737861 0.19604453 0.81094081 0.86011613
  0.5433478  0.63133729 0.9835536  0.50604448]
 [0.29550132 0.99010186 0.76380136 0.42256745 0.23257329 0.76691778
  0.49360522 0.05952806 0.1662249  0.95886168]
 [0.72091837 0.78893791 0.74065296 0.06841253 0.06104635 0.85996358
  0.59009193 0.15215498 0.31219422 0.50363681]
 [0.70049842 0.37905847 0.12204784 0.92399692 0.92052741 0.33168253
  0.27967555 0.25081877 0.06735712 0.71850832]
 [0.72764155 0.77609094 0.71020386 0.10180146 0.11453646 0.02980189
  0.0309191  0.15395231 0.54755611 0.57844997]
 [0.34450448 0.54653892 0.92750977 0.38800861 0.58017167 0.32855266
  0.33143986 0.99578179 0.05626356 0.37638427]
 [0.06907416 0.50815107 0.46972478 0.99646776 0.0946219  0.89632523
  0.76038329 0.78603988 0.45483133 0.49232992]
 [0.4114731  0.49149234 0.40889981 0.80795832 0.90240004 0.41547976
  0.32329042

(9, 4)

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [166]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code
print('X=', X, '\n', 'y= ', y)
idx = np.argmin(np.linalg.norm(X-y, axis = 1))
print('closest point index = ', idx)
print('closest point=', X[idx])

X= [[0.93889864 0.27855441]
 [0.78177228 0.53501996]
 [0.16513856 0.30804717]
 [0.32951119 0.41227249]
 [0.61010486 0.89769344]
 [0.41831909 0.0017831 ]
 [0.42945662 0.15549907]
 [0.89695652 0.16360867]
 [0.88957086 0.27791552]
 [0.76512813 0.28497497]] 
 y=  [[0.14589434 0.32343936]]
closest point index =  2
closest point= [0.16513856 0.30804717]


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [164]:
## your code
X = np.arange(-3, 3.1, 0.1)
@np.vectorize
def f(x):
    if x<0:
        return x**2+2*x+6
    elif x<=2:
        return x+6
    else:
        return x**2+4*x-4
f(X)

array([ 9.  ,  8.61,  8.24,  7.89,  7.56,  7.25,  6.96,  6.69,  6.44,
        6.21,  6.  ,  5.81,  5.64,  5.49,  5.36,  5.25,  5.16,  5.09,
        5.04,  5.01,  5.  ,  5.01,  5.04,  5.09,  5.16,  5.25,  5.36,
        5.49,  5.64,  5.81,  6.  ,  6.1 ,  6.2 ,  6.3 ,  6.4 ,  6.5 ,
        6.6 ,  6.7 ,  6.8 ,  6.9 ,  7.  ,  7.1 ,  7.2 ,  7.3 ,  7.4 ,
        7.5 ,  7.6 ,  7.7 ,  7.8 ,  7.9 ,  8.  ,  8.81,  9.64, 10.49,
       11.36, 12.25, 13.16, 14.09, 15.04, 16.01, 17.  ])

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [184]:
X = np.random.random((10, 10))

## your code

means = np.mean(X, axis = 1)  # means of each row 
answer = X - (np.ones((10,10))*means).T

print('check if means of each row are zeros:\n', np.mean(answer, axis=1))

check if means of each row are zeros:
 [-4.44089210e-17  3.33066907e-17 -2.22044605e-17 -8.88178420e-17
 -1.11022302e-17  2.22044605e-17  1.11022302e-17  5.55111512e-17
 -2.22044605e-17 -2.22044605e-17]


**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [28]:
X = np.random.normal(loc=5, scale=2., size=1000)
np.mean(X), np.var(X)

(5.066452596047016, 4.026655486996178)

**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [71]:
## your code
np.indices((5,5)).sum(axis=0) % 5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [23]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 1, 0, 2]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [24]:
## your code

def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    values = np.random.random(c) * s
    cumsum = np.transpose([np.cumsum(x)])
    ans = np.argmax((values < cumsum).T, axis = 1)
    return ans

In [25]:
sample([50, 3, 1, 7, 20], 5)   

array([0, 1, 4, 0, 4], dtype=int64)